---
title: Integration of multiple experiments for the ccRCC project
author: 
- name: Nick Borcherding
  email: ncborch@gmail.com
  affiliation: Washington University in St. Louis, School of Medicine, St. Louis, MO, USA
date: "July 13, 2020"
output:
  BiocStyle::html_document:
    toc_float: true
---

```{r, echo=FALSE, results="hide", message=FALSE}
knitr::opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
library(BiocStyle)
```


# Preperation

## Loading Libaries

In general I like to load libraries here that we will use universally, and then call other libraries when we need them in the code chunks that are relevant. 

```{r}
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(dplyr))
```

Differential Genes
```{r}
CD8.Tcells <- read.delim("./DataAnalysis/CellType/CD8.Tcells/FindAllMarkers.txt")
CD8.Tcells$Cells <- "CD8.Tcells"
APC <- read.delim("./DataAnalysis/CellType/APC/Macrophage/FindAllMarkers.txt")
APC$Cells <- "APC"
combined <- rbind.data.frame(CD8.Tcells, APC)
combined$classifier <- paste0(combined$Cells, "_", combined$cluster)
```

Filtering Genes
```{r}
unique <- unique(combined$classifier)
gene_list <- NULL
for (i in seq_along(unique)) {
    tmp <- subset(combined, classifier == unique[i])
    tmp$difference <- tmp$pct.1 - tmp$pct.2
    tmp1 <- tmp[tmp$avg_logFC > 0.5, ]
    tmp1 <- tmp1$gene
    tmp2 <- tmp[tmp$avg_logFC > 0.5 & tmp$difference > 0.15, ]
    tmp2 <- tmp2$gene
    gene_list[[i]] <- list(tmp1, tmp2)
}
names(gene_list) <- unique

genes <- unique(unlist(gene_list))
```



TCGA data

```{r}
ccRCC_RNA <- read.delim("./ML/KIRC_HiSeqV2.txt", check.names = F)
updated_survival <- read.delim("./ML/updated_survival.txt")
```

Filtering 

RNA
```{r}
#Removing normal tissue samples and metastasis samples
ccRCC_RNA <- ccRCC_RNA[,!grepl("-05|-06|-11",colnames(ccRCC_RNA))]

#Isolating just the genes in the differential list
ccRCC_RNA <- ccRCC_RNA[ccRCC_RNA$sample %in% genes,]
```

Clinical Information
```{r}
samples <- colnames(ccRCC_RNA)[2:534]
samples <- stringr::str_remove(samples, "-01")

updated_survival <- updated_survival[updated_survival$bcr_patient_barcode %in% samples,]
```


```{r}
clinical <- updated_survival[,c("bcr_patient_barcode","OS", "DSS", "DFI", "PFI")]
data <- as.data.frame(t(ccRCC_RNA))
colnames(data) <- data[1,]
data <- data[-1,]
rownames(data) <- stringr::str_remove(rownames(data), "-01")
data <- merge(data, clinical, by.x = "row.names", by.y = "bcr_patient_barcode")
```

### Generating Models

```{r}
survival <- c("OS", "DSS", "DFI", "PFI")
```

```{r}
dir.create("./ML/models")
```


```{r}
set.seed(123)
out <- NULL
library(doParallel)
registerDoParallel(cores=4)

for (i in seq_along(survival)) {
    partition <- caret::createDataPartition(data[,survival[i]], p=0.5, list=F)
    train <- data[partition,]
    test <- data[-partition,]
    #Loop for all the gene lists
    for (j in seq_along(gene_list)) {
        genes <- gene_list[[j]][[2]]
        tmp <- train[,colnames(train) %in% c(survival[i], genes)]
        tmp[] <- lapply(tmp[], function(x) as.numeric(as.character(x)))
        #Fine-tuning parameters for rfeControl - feature selection
        rctrl1 <- rfeControl(returnResamp = "all", functions = caretFuncs, saveDetails = TRUE, method="repeatedcv", number=10, repeats=16)
        length = ncol(tmp)-1
      
        rf_grid <-  expand.grid(mtry = c(floor(sqrt(ncol(tmp)) / 10),
                        floor(sqrt(ncol(tmp)) / 5),
                        floor(sqrt(ncol(tmp)))))
        #Creating the model
        model <- rfe(as.factor(tmp[,survival[i]]) ~ ., data = as.matrix(tmp[,1:length]),
             sizes = c(1, 5, 10, 15, 20),
             method='rf', 
             preProcess = c("scale", "center"),
             rfeControl = rctrl1)
      model_importance <- varImp(model)
      model_importance$names <- rownames(model_importance)
      model_importance <- model_importance[1:model$bestSubset,]
      
    
      plot <- ggplot(model_importance, aes(x=reorder(names, Overall), y=Overall)) +
        geom_bar(stat="identity") +
        coord_flip() + 
        theme_classic()
      ggsave(path = "./ML/models/", filename=paste(names(gene_list)[i], "_VarImp.pdf", sep=""), plot, height=3, width=3)
        
          
      eval <- test[,colnames(test) %in% c(survival[i], genes)]
      eval[] <- lapply(eval[], function(x) as.numeric(as.character(x)))
      predictions <- predict(model, newdata = as.matrix(eval[,1:length]))
      
      results <- data.frame(actual = eval[,survival[i]], predict = predictions)
      results <- results %>%
        mutate(correct = ifelse(actual == predict, TRUE, FALSE))
      plot <- ggplot(results, aes(x = predict, fill = correct)) +
            geom_bar(position = "fill") + 
            theme_classic()
      ggsave(paste("./ML/models/", names(gene_list)[i], ".pdf", sep=""), plot, height=3, width=3)
      
       y <- confusionMatrix(predict(model, newdata = as.matrix(eval[,1:length])), reference = as.factor(eval[,survival[i]]))
      row <- unlist(c(y$overall[c(1:4,6)], y$table[1], y$table[2], y$table[3], y$table[4], y$byClass[1:4], names(gene_list[j]), survival[i]))
    out <- rbind(out,row) 
    save(model, file = paste0(survival[i], "_", names(gene_list[j]), ".rda"))
    }
   
}
colnames(out) <- c("Accuracy", "Kappa", "Accur_low", "Accur_high", "Pvalue", "TP", "FN", "FP", "TN", "Sensitivity", "Specificity", "PPV", "NPV", "Celltype", "GeneSize")
write.table(mat, file="./ML/models/model_summaries.txt", sep="\t",append=F, row.names = F)

stopImplicitCluster()
```

```{r}
library(skimr)
skimmed <- skim_to_wide(trainData)
skimmed[, c(1:5, 9:11, 13, 15:16)]
```

```{r}
dfTPM$condition <- as.factor(dfTPM$condition)
set.seed(123)
index <- caret::createDataPartition(dfTPM$condition, p=0.5, list=F)


```

```{r}
fs <- Boruta::Boruta(train$ ~ ., data=scale(train[]))
fnames <- Boruta::getSelectedAttributes(fs)
fnames
```


```{r}
Btrain <- train[,colnames(train) %in% fnames]
Btrain$condition <- train$condition
```

```{r}
library(mlbench)
library(caret)
library(dplyr)

control <- caret::trainControl(method="repeatedcv", number=10, repeats=128, selectionFunction = "best", savePredictions = T, classProbs = TRUE, summaryFunction = twoClassSummary)
grid <- expand.grid(mtry = c(1:10))

Model <- caret::train(train[,1:839], train$condition,
                method='rf', 
                preProcess = c("scale", "center"),
                trControl=control, 
                verbose=F)
predictions <- predict(Model, test)
results <- data.frame(actual = test$condition, predict = predictions)
results <- results %>%
            mutate(correct = ifelse(actual == predict, TRUE, FALSE))
ggplot2::ggplot(results, aes(x = predict, fill = correct)) +
            geom_bar(position = "fill") + 
            theme_classic()

 model_importance <- varImp(Model)
 print(plot(model_importance))
```
```

